# Generated by Django 5.1.4 on 2025-01-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='rooms_included',
        ),
        migrations.AddField(
            model_name='residence',
            name='rooms_include',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
