# Generated by Django 5.1.4 on 2025-01-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0003_alter_image_image_alter_residence_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='extra_images/'),
        ),
    ]
