# Generated by Django 5.1.4 on 2025-01-05 16:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='is_images_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residence',
            name='is_on_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residence',
            name='is_videos_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residence',
            name='reference_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='residence',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
