# Generated by Django 5.1.4 on 2025-01-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0005_residence_is_images_subscribed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reference_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
