# Generated by Django 5.1.4 on 2025-01-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0007_remove_residence_is_images_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='business_contacts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
